---
title: "Instructions"
author: "_AUTHOR_NAME_"
date: "8/10/2020"
output: html_document
---
## R Shiny App
By default the shiny app is created and linked to an R package.  If the app does not need complex computation you can remove the call to load the library in the Global.R file.  A couple important points:

@) Before the app will run you must first build the R library or remove the call to load the library, see next item.
@) To remove the dependency on the R library, remove the library call in Global.R
@) ShinyUI.R - Contain several options to modify such as a) Application name, b) Author name, c) Contact info and d) release date. 
    + Contains the sidebar object that setup the navigation bar on the left.
    + Contains the Body element which is the main content created via Modules.   
    + To view modules refer to the Modules folder.
@) Each tab  should be created via modules.   Each module is contained in the Modules folder and contains a ModuleNameUI.R and ModuleNameServer.R pair of files to create the UI and the server for each tab. 
@) Modules/DataAnalysisRunAnalysisServer.R - This file contains the example of how to call a function in the the R package.  This approach would be the same to call any function in a package. 

To launch the Shiny App, open the ShinyApp.R file, then click the button that says "Run App".


You may find the following functions in the BaSS package helpful when you developing the Shiny app. 

AddNewTabToApp( strTabName, vSubMenuItemNames ) - This function will add a new tab to the Shiny App. This function assumes that the working directory
is the main directory of the Shiny app created by this package.  This function creates a module file for the UI and the Server in the Modules directory
of the app, it alters the ShinyUI.R file to insert the calls to  modules so the tab is added to the UI. 
